### ISSUE TITLE
gmm_notes.pdf has incorrect identification examples

### ISSUE THREAD

**Issue by artrw** [ligonteaching/ARE212_Materials#5]
gmm_notes.pdf says that if k<l, a model is under-identified and if k>l, then it is over-identified, when it should be the reverse.

**Comment by ligon** [comment]
Thanks!  That was actually pointed out in lecture, as I recall, but
apparently I need to be reminded twice.

-Ethan

**Comment by ligon** [comment]
Fixed in commit 3e2f9b7acae8d6dc6c9aaee685efe5c9204ec6c3.
