### ISSUE TITLE
Issues from lecture

### ISSUE THREAD

**Issue by artrw** [ligonteaching/ARE212_Materials#6]
This notebook still needs to updated to include the line
!pip install CFEDemands --pre

and to resolve the double-squaring of the error term.

**Comment by ligon** [comment]
I think the notebook you're referring to is linear-non-linear.ipynb, which I've just re-built so that it eliminates the dependency on CFEDemands.

**Comment by ligon** [comment]
If that's correct then commit aad56cac98d7e69c21ba94e671c81c8180c90489 addresses the two issues you mention, so I'm closing this.  Please re-open if I've got the wrong file.
